#!/usr/bin/env python3
"""
Fit per-channel logit-space affine calibration for pretrain_contact from freerun JSONs.

The fitted payload can be passed to:
  train.validate.run_freerun_cycles --contacts_meas_pretrain_affine_stats <json>

Expected input JSONs are generated by run_freerun_cycles with --log_contacts and
contacts_meas_source=pretrain_contact (typically clamp1 baseline).
"""

from __future__ import annotations

import argparse
import glob
import json
import math
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import numpy as np


def _expand_json_specs(specs: Sequence[str], *, pattern: str = "*_freerun_cycles.json") -> List[Path]:
    out: List[Path] = []
    seen: set[Path] = set()
    for spec in specs:
        if not spec:
            continue
        s = os.path.expanduser(str(spec))
        matches: List[Path] = []
        if any(ch in s for ch in "*?[]"):
            matches = [Path(p) for p in glob.glob(s)]
        else:
            p = Path(s)
            if p.is_dir():
                matches = sorted(p.glob(pattern))
            elif p.is_file():
                matches = [p]
        for m in matches:
            try:
                r = m.resolve()
            except Exception:
                r = m
            if r.is_file() and r not in seen:
                seen.add(r)
                out.append(r)
    return sorted(out)


def _as_float_list(x: Any) -> Optional[List[float]]:
    if not isinstance(x, list) or not x:
        return None
    out: List[float] = []
    for v in x:
        try:
            fv = float(v)
        except Exception:
            return None
        if not math.isfinite(fv):
            return None
        out.append(fv)
    return out


def _logit(p: np.ndarray, eps: float) -> np.ndarray:
    q = np.clip(p, eps, 1.0 - eps)
    return np.log(q) - np.log1p(-q)


def _sigmoid(x: np.ndarray) -> np.ndarray:
    # Stable sigmoid.
    y = np.empty_like(x, dtype=np.float64)
    pos = x >= 0
    neg = ~pos
    y[pos] = 1.0 / (1.0 + np.exp(-x[pos]))
    ex = np.exp(x[neg])
    y[neg] = ex / (1.0 + ex)
    return y


def _fit_affine(x: np.ndarray, y: np.ndarray) -> Tuple[float, float]:
    if x.size == 0 or y.size == 0:
        return 1.0, 0.0
    A = np.stack([x, np.ones_like(x)], axis=1)
    sol, _, _, _ = np.linalg.lstsq(A, y, rcond=None)
    s = float(sol[0])
    b = float(sol[1])
    if not math.isfinite(s):
        s = 1.0
    if not math.isfinite(b):
        b = 0.0
    return s, b


def _mean(xs: Sequence[float]) -> Optional[float]:
    if not xs:
        return None
    arr = np.asarray(list(xs), dtype=np.float64)
    if arr.size == 0:
        return None
    return float(arr.mean())


def _fmt(x: Optional[float], nd: int = 6) -> str:
    if x is None:
        return "-"
    return f"{x:.{nd}f}"


def main() -> int:
    ap = argparse.ArgumentParser(description="Fit pretrain_contact affine calibration from freerun JSONs.")
    ap.add_argument("--json", nargs="+", required=True, help="Paths/dirs/globs to *_freerun_cycles.json.")
    ap.add_argument(
        "--round-gte",
        type=int,
        default=1,
        help="Only use steps with round >= this value (implemented via step >= round_gte * cycle_len when cycle_len>0).",
    )
    ap.add_argument(
        "--require-source-prefix",
        type=str,
        default="pretrain_contact",
        help="If non-empty, keep steps whose ContactsMeasSourceApplied starts with this prefix.",
    )
    ap.add_argument(
        "--target",
        type=str,
        default="gt",
        choices=("gt", "plan", "mix"),
        help="Calibration target: gt=ContactGTPerC, plan=ContactPlanPerC, mix=(1-a)*gt + a*plan.",
    )
    ap.add_argument(
        "--mix-alpha",
        type=float,
        default=0.5,
        help="When --target=mix, target = (1-alpha)*gt + alpha*plan. Range [0,1].",
    )
    ap.add_argument("--eps", type=float, default=1e-4, help="Clamp epsilon for logit transform.")
    ap.add_argument(
        "--out-json",
        type=str,
        default="debug_output/_tmp_pretrain_contact_affine_fit/affine_stats.json",
        help="Output JSON path.",
    )
    ap.add_argument(
        "--out-md",
        type=str,
        default="debug_output/_tmp_pretrain_contact_affine_fit/summary.md",
        help="Output markdown summary path.",
    )
    args = ap.parse_args()

    eps = float(args.eps)
    if not math.isfinite(eps):
        eps = 1e-4
    eps = float(min(1e-2, max(1e-8, eps)))

    paths = _expand_json_specs(args.json)
    if not paths:
        raise SystemExit("[FATAL] No freerun JSON matched --json specs.")

    src_prefix = str(args.require_source_prefix or "").strip()
    round_gte = max(0, int(args.round_gte))
    target_mode = str(args.target or "gt").strip().lower()
    mix_alpha = float(args.mix_alpha)
    if not math.isfinite(mix_alpha):
        mix_alpha = 0.5
    mix_alpha = float(max(0.0, min(1.0, mix_alpha)))

    meas_cols: Optional[List[List[float]]] = None
    gt_cols: Optional[List[List[float]]] = None
    used_files = 0
    used_steps = 0
    skipped_steps = 0

    per_file_stats: List[Dict[str, Any]] = []

    for p in paths:
        data = json.loads(p.read_text(encoding="utf-8"))
        steps = data.get("metrics_per_step", None)
        if not isinstance(steps, list):
            continue
        cycle_len = int(data.get("cycle_len", 0) or 0)
        step_floor = int(round_gte * cycle_len) if cycle_len > 0 else 0

        file_used = 0
        for idx, st in enumerate(steps):
            if not isinstance(st, dict):
                skipped_steps += 1
                continue
            step = int(st.get("step", idx) or idx)
            if step < step_floor:
                skipped_steps += 1
                continue
            if src_prefix:
                sap = str(st.get("ContactsMeasSourceApplied", "") or "")
                if not sap.startswith(src_prefix):
                    skipped_steps += 1
                    continue
            meas = _as_float_list(st.get("ContactMeasPerC"))
            gt = _as_float_list(st.get("ContactGTPerC"))
            plan = _as_float_list(st.get("ContactPlanPerC"))
            if meas is None or gt is None or len(meas) != len(gt):
                skipped_steps += 1
                continue
            C = len(meas)
            if C <= 0:
                skipped_steps += 1
                continue
            if target_mode in ("plan", "mix"):
                if plan is None or len(plan) != C:
                    skipped_steps += 1
                    continue
            if meas_cols is None:
                meas_cols = [[] for _ in range(C)]
                gt_cols = [[] for _ in range(C)]
            if gt_cols is None or len(meas_cols) != C or len(gt_cols) != C:
                skipped_steps += 1
                continue
            for c in range(C):
                meas_cols[c].append(float(meas[c]))
                if target_mode == "gt":
                    tgt = float(gt[c])
                elif target_mode == "plan":
                    tgt = float(plan[c]) if isinstance(plan, list) else float(gt[c])
                else:
                    pv = float(plan[c]) if isinstance(plan, list) else float(gt[c])
                    tgt = float((1.0 - mix_alpha) * float(gt[c]) + mix_alpha * pv)
                gt_cols[c].append(tgt)
            used_steps += 1
            file_used += 1

        if file_used > 0:
            used_files += 1
            per_file_stats.append({"json": str(p), "used_steps": int(file_used), "cycle_len": int(cycle_len)})

    if meas_cols is None or gt_cols is None:
        raise SystemExit("[FATAL] No valid samples found (check source/round filters).")

    C = len(meas_cols)
    scale: List[float] = []
    bias: List[float] = []
    per_channel: List[Dict[str, Any]] = []

    before_abs_all: List[float] = []
    after_abs_all: List[float] = []

    for c in range(C):
        meas = np.asarray(meas_cols[c], dtype=np.float64)
        gt = np.asarray(gt_cols[c], dtype=np.float64)
        x = _logit(meas, eps=eps)
        y = _logit(gt, eps=eps)
        s, b = _fit_affine(x, y)
        scale.append(float(s))
        bias.append(float(b))

        pred_before = np.clip(meas, 0.0, 1.0)
        pred_after = _sigmoid(b + s * x)

        abs_before = np.abs(pred_before - gt)
        abs_after = np.abs(pred_after - gt)
        before_abs_all.extend(abs_before.tolist())
        after_abs_all.extend(abs_after.tolist())

        per_channel.append(
            {
                "channel": int(c),
                "n": int(meas.size),
                "scale": float(s),
                "bias": float(b),
                "contact_err_abs_mean_before": float(abs_before.mean()) if abs_before.size else None,
                "contact_err_abs_mean_after": float(abs_after.mean()) if abs_after.size else None,
            }
        )

    payload: Dict[str, Any] = {
        "kind": "pretrain_contact_affine",
        "space": "logit",
        "fitted_at_utc": datetime.now(timezone.utc).isoformat(),
        "eps": float(eps),
        "round_gte": int(round_gte),
        "require_source_prefix": src_prefix,
        "target": str(target_mode),
        "mix_alpha": float(mix_alpha),
        "num_files_total": int(len(paths)),
        "num_files_used": int(used_files),
        "num_steps_used": int(used_steps),
        "num_steps_skipped": int(skipped_steps),
        "scale": scale,
        "bias": bias,
        "metrics": {
            "contact_err_abs_mean_before": _mean(before_abs_all),
            "contact_err_abs_mean_after": _mean(after_abs_all),
            "contact_err_abs_mean_delta": (
                (_mean(after_abs_all) - _mean(before_abs_all))
                if _mean(before_abs_all) is not None and _mean(after_abs_all) is not None
                else None
            ),
        },
        "per_channel": per_channel,
        "inputs": [str(p) for p in paths],
        "files_used": per_file_stats,
    }

    out_json = Path(args.out_json).expanduser()
    out_md = Path(args.out_md).expanduser()
    out_json.parent.mkdir(parents=True, exist_ok=True)
    out_md.parent.mkdir(parents=True, exist_ok=True)
    out_json.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    m = payload.get("metrics", {})
    lines: List[str] = []
    lines.append("# pretrain_contact affine fit from freerun")
    lines.append("")
    lines.append("## Setup")
    lines.append(f"- json specs resolved: {len(paths)}")
    lines.append(f"- files used: {payload['num_files_used']}")
    lines.append(f"- steps used: {payload['num_steps_used']}")
    lines.append(f"- round_gte: {round_gte}")
    lines.append(f"- source prefix filter: `{src_prefix or '(none)'}`")
    lines.append(f"- target: `{target_mode}`")
    if target_mode == "mix":
        lines.append(f"- mix_alpha: {mix_alpha}")
    lines.append(f"- eps: {eps}")
    lines.append("")
    lines.append("## Aggregate")
    lines.append(f"- ContactErrAbsMean before: {_fmt(m.get('contact_err_abs_mean_before'))}")
    lines.append(f"- ContactErrAbsMean after: {_fmt(m.get('contact_err_abs_mean_after'))}")
    lines.append(f"- delta(after-before): {_fmt(m.get('contact_err_abs_mean_delta'))}")
    lines.append("")
    lines.append("## Per-channel affine")
    lines.append("| channel | n | scale | bias | AbsErr before | AbsErr after |")
    lines.append("|---:|---:|---:|---:|---:|---:|")
    for r in per_channel:
        lines.append(
            f"| {int(r['channel'])} | {int(r['n'])} | {_fmt(r.get('scale'))} | {_fmt(r.get('bias'))} | "
            f"{_fmt(r.get('contact_err_abs_mean_before'))} | {_fmt(r.get('contact_err_abs_mean_after'))} |"
        )
    lines.append("")
    lines.append("## Output")
    lines.append(f"- stats json: `{out_json}`")
    out_md.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"[done] wrote {out_json}")
    print(f"[done] wrote {out_md}")
    print(
        "[overall] ContactErrAbsMean "
        f"before={_fmt(m.get('contact_err_abs_mean_before'))} "
        f"after={_fmt(m.get('contact_err_abs_mean_after'))} "
        f"delta={_fmt(m.get('contact_err_abs_mean_delta'))}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
